version: '2'
services:
  eventplanner-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/EventPlanner/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=EventPlanner
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
